version: '2'
services:
  data:
    image: glycoinfo.org:5000/${PROJECT_NAME}:${BATCH_VERSION}
    command: echo "binaries ready"
    volumes:
      - /data
  batch:
    image: java:8u91-jdk
    working_dir: /data
    command: java -jar ${PROJECT_NAME}-${BATCH_VERSION}.jar
    volumes:
      - /home/jenkins/batch/${PROJECT_NAME}:/root/batch/${PROJECT_NAME}
    volumes_from:
      - data
    environment:
      - PROJECT=${PROJECT_NAME}
      - HOME=/root/batch/${PROJECT_NAME}
      - SPRING_TRIPLESTORE_URL
      - SPRING_TRIPLESTORE_PASSWORD
